dist: trusty

language: csharp

script:
    - sudo apt-get install python3
    - sudo apt-get install python3-pip
    - python3 -m pip install mypy antlr4-python3-runtime
    - wget https://github.com/jonathanvdc/compare-test/releases/download/v0.1.4/compare-test.zip
    - mkdir compare-test
    - unzip compare-test.zip -d compare-test
    - mono compare-test/compare-test.exe src/test/all.test
